import{useEffect,useRef,useState}from'react';import gsap from'gsap';import{ScrollTrigger}from'gsap/ScrollTrigger';import{story}from'./data.js';gsap.registerPlugin(ScrollTrigger);
function Img({src,alt,hero=false}){return <img src={src} alt={alt} loading={hero?'eager':'lazy'} fetchPriority={hero?'high':'auto'}/>}
export default function App(){const[entered,setEntered]=useState(false);const root=useRef(null);useEffect(()=>{document.body.style.overflow=entered?'':'hidden';if(!entered)scrollTo(0,0);return()=>document.body.style.overflow=''},[entered]);useEffect(()=>{if(!entered||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const c=gsap.context(()=>{gsap.utils.toArray('.reveal').forEach(el=>gsap.fromTo(el,{y:30,opacity:0},{y:0,opacity:1,duration:.9,ease:'power3.out',scrollTrigger:{trigger:el,start:'top 86%',once:true}}));gsap.utils.toArray('.float').forEach(el=>gsap.to(el,{y:-28,scrollTrigger:{trigger:el,scrub:.7}}))},root);return()=>c.revert()},[entered]);return <main ref={root} className="shell">
{!entered&&<section className="entry"><div className="dial">RR</div><p>BRIDAL BRUNCH · LIVE</p><h1>Rosewater<br/>Radio</h1><button onClick={()=>setEntered(true)}>Tune in</button><small>{story.couple.date} · {story.couple.location}</small></section>}
<div className={entered?'story live':'story'} aria-hidden={!entered}>
<section className="scene hero"><Img hero src={story.photos[0]} alt="Bridal celebration"/><div className="wash"/><div className="hero-copy reveal"><p>{story.scenes[0][0]}</p><h2>{story.scenes[0][1]}</h2><span>{story.scenes[0][2]}</span></div><div className="ticker">ROSEWATER RADIO • BRUNCH TRANSMISSION • DELHI • </div></section>
<section className="scene split cream"><div className="copy reveal"><p>{story.scenes[1][0]}</p><h2>{story.scenes[1][1]}</h2><span>{story.scenes[1][2]}</span></div><div className="arch float"><Img src={story.photos[1]} alt="Brunch details"/></div></section>
<section className="scene portrait pine"><div className="photo-card reveal"><Img src={story.photos[2]} alt="Portrait"/></div><div className="copy reveal"><p>{story.scenes[2][0]}</p><h2>{story.scenes[2][1]}</h2><span>{story.scenes[2][2]}</span></div></section>
<section className="scene menu"><div className="menu-card reveal"><b>ON AIR / 04</b><h2>{story.scenes[3][1]}</h2><p>{story.scenes[3][2]}</p></div><div className="menu-photo"><Img src={story.photos[3]} alt="Table setting"/></div></section>
<section className="scene chorus pine"><div className="grid"><Img src={story.photos[4]} alt="Friends celebrating"/><Img src={story.photos[1]} alt="Friends portrait"/><Img src={story.photos[5]} alt="Celebration detail"/></div><div className="caption reveal"><p>{story.scenes[4][0]}</p><h2>{story.scenes[4][1]}</h2></div></section>
<section className="scene side-a"><div className="disc float">A</div><div className="copy reveal"><p>{story.scenes[5][0]}</p><h2>{story.scenes[5][1]}</h2><span>{story.scenes[5][2]}</span></div></section>
<section className="scene dedication cream"><div className="copy reveal"><p>{story.scenes[6][0]}</p><h2>{story.scenes[6][1]}</h2><span>{story.scenes[6][2]}</span></div><Img src={story.photos[4]} alt="Family celebration"/></section>
<section className="scene side-b"><Img src={story.photos[0]} alt="Brunch party"/><div className="wash rose"/><div className="copy reveal"><p>{story.scenes[7][0]}</p><h2>{story.scenes[7][1]}</h2><span>{story.scenes[7][2]}</span></div></section>
<section className="scene contacts cream"><div className="contact-head reveal"><p>{story.scenes[8][0]}</p><h2>{story.scenes[8][1]}</h2></div>{[0,1,2,3,4,5].map((i)=><Img key={i} src={story.photos[i]} alt={`Contact frame ${i+1}`}/>)}</section>
<section className="scene window pine"><Img src={story.photos[2]} alt="Window portrait"/><div className="copy reveal"><p>{story.scenes[9][0]}</p><h2>{story.scenes[9][1]}</h2><span>{story.scenes[9][2]}</span></div></section>
<section className="scene signoff"><div className="frequency">FM 06.02</div><div className="copy reveal"><p>{story.scenes[10][0]}</p><h2>{story.scenes[10][1]}</h2><span>{story.scenes[10][2]}</span></div></section>
<section className="scene finale cream"><p>{story.scenes[11][0]}</p><h2>{story.scenes[11][1]}</h2><span>{story.scenes[11][2]}</span><div className="meta">{story.couple.name} · {story.couple.date}<b>ROSEWATER RADIO</b></div></section>
</div></main>}
